CREATE TABLE venta (
    id SERIAL PRIMARY KEY,
    tipo_identificacion_cliente VARCHAR(2),
    no_identificacion_cliente VARCHAR(13),
    parte_relacionada VARCHAR(2),
    tipo_cliente VARCHAR(2),
    razon_social_cliente VARCHAR(500),
    codigo_tipo_comprobante VARCHAR(3),
    tipo_emision VARCHAR(1),
    no_serie_comprobante_venta_establecimiento VARCHAR(3),
    no_serie_comprobante_venta_punto_emision VARCHAR(3),
    no_secuencial_comprobante_venta VARCHAR(9),
    base_imponible_no_objeto_iva DECIMAL(14,2),
    base_imponible_tarifa_0 DECIMAL(14,2),
    base_imponible_tarifa_iva_diferente_0 DECIMAL(14,2),
    monto_iva DECIMAL(14,2),
    tipo_compensaciones VARCHAR(2),
    monto_compensaciones DECIMAL(14,2),
    monto_ice DECIMAL(14,2),
    valor_iva_retenido DECIMAL(14,2),
    valor_renta_retenido DECIMAL(14,2),
    forma_cobro VARCHAR(2),
    codigo_establecimiento VARCHAR(3),
    ventas_generadas_establecimiento DECIMAL(14,2),
    iva_compensado_establecimiento_ventas_ley_solidaridad DECIMAL(14,2),
    usuario VARCHAR(50),
    fecha DATE,
    descripcion VARCHAR(50),
    detalle VARCHAR(50),
    ccostos VARCHAR(50),
    ibeneficiario VARCHAR(50),
    cuenta_iva_base VARCHAR(50),
    cuenta_ingreso_base VARCHAR(50),
    formulario_base_imponible_15 VARCHAR(50),
    cuenta_iva VARCHAR(50),
    cuenta_ingreso VARCHAR(50),
    sistema VARCHAR(1),
    sistema_tipo_documento VARCHAR(3)
);

CREATE INDEX idx_fecha_venta ON venta(fecha_venta);